In [8]:
import __init__
from utils.pipelines import *

In [9]:
db_path = 'data/female_names/1551_1900/results.db'

dir = os.path.dirname(db_path)

output_dir = f'{dir}/output'
big_names_path = f'{output_dir}/big_names.xlsx'
saved_names_path = f'{output_dir}/saved_names.xlsx'
big_and_saved_names_path = f'{output_dir}/big_and_saved_names.xlsx'

In [10]:
prepare_output_dir(output_dir)

Подготовка выходной директории
Создана директория data/female_names/1551_1900/output

In [13]:
saved_names = get_saved_names(db_path, saved_names_path)
saved_names

        name
0    Петимат
1      Петра
2       Пика
3         По
4       Поли
..       ...
190    Сарра
191   Сарсен
192   Сархан
193   Сарюна
194     Сати

[195 rows x 1 columns]

In [14]:
big_names = get_big_names(db_path, big_names_path)
big_names

     name
0  Полина
1    Саня

In [15]:
big_and_saved_names = get_big_and_saved_names(db_path, big_and_saved_names_path)
big_and_saved_names

        name
0    Петимат
1      Петра
2       Пика
3         По
4       Поли
..       ...
192    Сарра
193   Сарсен
194   Сархан
195   Сарюна
196     Сати

[197 rows x 1 columns]

In [17]:
cabinets = get_cabinets(db_path)
cabinets

  cabinet
0  Полина